version: '3'
services:
  php-api:
    build:
      context: ./BDD_Creator
    ports:
      - "80:80"
    volumes:
      - ./BDD_Creator:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    # networks:
    #   - app-network

  react-frontend:
    build:
      context: ./front_bdd_creator
    ports:
      - "3000:3000"
    volumes:
      - ./front_bdd_creator:/app
      - ./front_bdd_creator/node_modules:/app/node_modules
    depends_on:
      - php-api
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV="development"
    # networks:
    #   - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    # networks:
    #   - app-network

volumes:
  mysql-data:

# networks:
#   app-network: