
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v3

      # 2. Set up Docker Compose and build the containers
      - name: Set up Docker
        run: |
          docker-compose -f docker-compose.yml up -d --build

      # 3. Run PHPUnit tests in the PHP container
      - name: Run PHPUnit tests
        run: |
          docker-compose exec bdd_depresion-php-api ./vendor/bin/phpunit tests

      # 4. Shut down Docker Compose after tests
      - name: Shut down Docker Compose
        run: |
          docker-compose down
