
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Set up PHP 8.2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # 2. Check out repository
      - uses: actions/checkout@v3

      # 3. Install Composer dependencies in BDD_Creator directory
      - name: Install dependencies
        working-directory: ./BDD_Creator
        run: composer install

      # 4. Autoload Composer
      - name: autoload composer
        working-directory: ./BDD_Creator
        run: composer dump-autoload

      # 5. Run npm install
      - name: npm install
        working-directory: ./front_bdd_creator
        run: npm install

      # 6. Run docker 
      - name: docker-compose up
        working-directory: ./
        run: docker-compose up -d

      # 4. Run PHPUnit tests
      - name: Run PHPUnit tests
        working-directory: ./BDD_Creator
        run: vendor/bin/phpunit tests
